#ifndef __IDS_H
#define __IDS_H

#define ID_APP_ICO 100
#define ID_APP_BNR 101
#define ID_APP_ICO_BIG 102

#define ID_FILE_NEW 1
#define ID_FILE_OPEN 2
#define ID_FILE_SAVE 3
#define ID_FILE_SAVE_AS 4
#define ID_FILE_EXIT 5

#define ID_HELP_REPO 6
#define ID_HELP_ABOUT 7

#define ID_FORMAT_FONT 8

#define ID_VIEW_ZOOM_IN 9
#define ID_VIEW_ZOOM_OUT 10
#define ID_VIEW_ZOOM_RESET 11

#define ID_EDIT_UNDO 12
#define ID_EDIT_CUT 13
#define ID_EDIT_COPY 14
#define ID_EDIT_PASTE 15
#define ID_EDIT_DELETE 16
#define ID_EDIT_GEMINI 17
#define ID_EDIT_FIND 18
#define ID_EDIT_FIND_NEXT 19
#define ID_EDIT_FIND_PREV 20
#define ID_EDIT_REPLACE 21
#define ID_EDIT_GOTO 22
#define ID_EDIT_SELECT_ALL 23
#define ID_EDIT_TIMENDATE 24

#define ID_CONTROL_EDIT 500
#define ID_CONTROL_STATUSBAR 501

#endif // __IDS_H