name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        uses: lukka/get-cmake@v3

      - name: Configure with CMake
        run: cmake -S . -B build -G "Visual Studio 16 2019"

      - name: Build with MSVC
        run: cmake --build build --config Release
