name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.21.3'

      - name: Install ninja
        run: choco install ninja

      - name: Configure with CMake
        run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=clang

      - name: Build with MSVC
        run: cmake --build build --config MinSizeRel