name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.21.3'

      - name: Install Ninja
        run: choco install ninja

      - name: Configure with CMake
        run: cmake ^ 
            -DCMAKE_BUILD_TYPE:STRING=MinSizeRel
            -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
            "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\clang.exe"
            "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\clang.exe" 
            --no-warn-unused-cli "-S." "-B./build" -G Ninja

      - name: Build with Clang
        run: cmake --build build --config Release -- -v
